---
apiVersion: v1
kind: Service
metadata:
  name: devpod
  annotations:
    load-balancer.hetzner.cloud/ipv6-disabled: "true"
    load-balancer.hetzner.cloud/location: ash
    external-dns.alpha.kubernetes.io/hostname: devpod-dev.k8s.unreliable.cloud
  labels:
    app: devpod
spec:
  selector:
    app: devpod
  ports:
  - port: 8000
    targetPort: 8000
  type: LoadBalancer
  externalTrafficPolicy: Cluster