# Allow deploying to k8s-us-east-1
allow_k8s_contexts('k8s-us-east-1')

# Always use docker hub
default_registry('docker.io/youvegotmoxie')

yamlBaseDir = "resources"

# Build container
docker_build(
  "devpod",
  context = '../docker',
  dockerfile = '../docker/Dockerfile',
  extra_tag='devpod:tilt-dev',
  live_update = [
    sync('../docker/src/templates', '/usr/src/app/templates'),
    sync('../docker/src/static', '/usr/src/app/static'),
    sync('../docker/src/requirements.txt', '/home/devpod/requirements.txt'),
    sync('../docker/src/app.py', '/usr/src/app/app.py'),
    sync('../docker/src/dev_pod.py', '/usr/src/app/dev_pod.py'),
    sync('../docker/src/helm', '/home/devpod/helm'),
    run (
      'pip3 install --no-cache-dir -r /home/devpod/requirements.txt',
      trigger = '../docker/src/requirements.txt'
    ),
    run(
      'chown -Rv devpod: /home/devpod/helm',
      trigger = '../docker/src/helm'
    )
  ]
)

# Keep container images in check
docker_prune_settings(keep_recent = 2, num_builds = 5)

# Deploy to k8s
k8s_yaml(['resources/deployment.yaml',
  'resources/service.yaml',
  'resources/clusterrolebinding.yaml',
  'resources/namespace.yaml',
  'resources/resourcequota.yaml',
  'resources/limitrange.yaml'])

k8s_resource(
  workload = 'devpod',
  labels = ['devpod'],
  objects=['devpod:serviceaccount:default',
    'devpod:clusterrolebinding',
    'devpod-deploy:namespace',
    'mem-cpu-limits:resourcequota',
    'mem-cpu-limits-pod:limitrange'],
  pod_readiness = 'wait'
)
