# Default values for dev-pod.

image:
  repository: docker.io/youvegotmoxie/ubuntu-jump
  pullPolicy: Always
  tag: "dev"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
securityContext: {}

service:
  type: LoadBalancer
  port: 22

resources:
  limits:
    cpu: "2"
  requests:
    cpu: 100m
    memory: 700Mi

nodeSelector: {}
tolerations: []
affinity: {}
