# Default values for dev-pod.

image:
  repository: docker.io/youvegotmoxie/ubuntu-jump
  pullPolicy: Always
  tag: "dev"

initContainer:
  image: docker.io/busybox:latest
  configDir: configs

job:
  image:
    repository: "docker.io/bitnami/kubectl"
    tag: "1.25.5"

devConfig:
  user: ubuntu
  repoPath: git
  shell: "/usr/bin/zsh"
  terminalFont: "MesloLGS NF"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

kubeApiServer: "5.161.160.176"

podAnnotations: {}

podSecurityContext: {}
securityContext: {}

service:
  type: LoadBalancer
  port: 22
  externalTrafficPolicy: Local

persistence:
  enabled: true
  storageClass: hcloud-volumes
  size: 50Gi

resources:
  limits:
    cpu: "2"
  requests:
    cpu: 100m
    memory: 700Mi

nodeSelector: {}
tolerations: []
affinity: {}
