apiVersion: apps/v1
kind: Deployment
metadata:
  name: devpod
spec:
  selector:
    matchLabels:
      app: devpod
  template:
    metadata:
      labels:
        app: devpod
    spec:
      containers:
      - name: devpod
        image: devpod
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8000
          name: http
        readinessProbe:
          httpGet:
            port: http