# Allow deploying to k8s-us-east-1
allow_k8s_contexts('k8s-us-east-1')

# Build container
docker_build(
  "docker.io/youvegotmoxie/devpod",
  context='../docker',
  dockerfile='../docker/Dockerfile',
  live_update=[
    sync('../docker/src/templates', '/usr/src/app/templates'),
    sync('../docker/src/static', '/usr/src/app/static'),
  ]
)

# Deploy to k8s
k8s_yaml(['deployment.yaml', 'service.yaml'])
k8s_resource(
  workload='devpod',
  #port_forwards='8000:8000',
  labels=['devpod']
)
