{{ $username := .Values.devConfig.user }}
{{ $shell := .Values.devConfig.shell | default "/bin/bash" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "dev-pod.labels" . | nindent 4 }}
  name: {{ .Release.Name }}-poststart
data:
  postStart.sh: |
    #!/bin/bash
    if [[ $(id {{ $username }}) ]]; then
      echo "startup script: {{ $username }} user already exists"
      exit 0
    else
      echo "startup script: configuring {{ $username }} user"
      useradd -c "{{ $username }} user" -d /home/{{ $username }} -m -s {{ $shell }} -G sudo {{ $username }}
      mkdir -p ~{{ $username }}/.ssh
      touch ~{{ $username }}/.zshrc
      echo -e "export GH_TOKEN=${GH_TOKEN}" > ~{{ $username }}/.github.token
      chmod 0700 ~{{ $username }}/.ssh
      cp /root/.ssh/authorized_keys ~{{ $username }}/.ssh/authorized_keys
      chmod 0600 ~{{ $username }}/.ssh/authorized_keys
      mkdir -p ~{{ $username }}/{{ .Values.devConfig.repoPath }}
    fi
    if [[ ! -f ~{{ $username }}/workspace.code-workspace ]]; then
      cp /configs/workspace.code-workspace ~{{ $username }}/workspace.code-workspace
    fi
    if [[ ! -f ~{{ $username }}/.ssh/id_ed25519 ]]; then
      cp /configs/id_ed25519 ~{{ $username }}/.ssh/id_ed25519
      chmod 0600 ~{{ $username }}/.ssh/id_ed25519
    fi
      chown -Rv {{ $username }}: ~{{ $username }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "dev-pod.labels" . | nindent 4 }}
  name: {{ .Release.Name }}-vscode-workspace
data:
  workspace.code-workspace: |
    {
      "folders": [
        {
          "path": "./{{ .Values.devConfig.repoPath }}"
        }
      ],
      "settings": {
        "files.enableTrash": false,
        "terminal.integrated.fontFamily": "{{ .Values.devConfig.terminalFont }}"
      }
    }
