---
apiVersion: v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "dev-pod.labels" . | nindent 4 }}
  name: {{ template "dev-pod.fullname" . }}-label-ns-job
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ template "dev-pod.fullname" . }}-label-ns-job"
subjects:
- kind: ServiceAccount
  name: "{{ template "dev-pod.fullname" . }}-label-ns-job"
  namespace: {{ .Release.Namespace }}