---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "dev-pod.fullname" . }}-label-ns-job
  labels:
    {{- include "dev-pod.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  backoffLimit: 1
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: {{ template "dev-pod.fullname" . }}-job
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: label-ns
        image: {{ .Values.job.image.repository }}:{{ .Values.job.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["sh", "-c", "kubectl label namespace {{ .Release.Namespace }} --overwrite app.kubernetes.io/dev-pod={{ .Release.Name }}"]
      serviceAccountName: {{ template "dev-pod.fullname" . }}-label-ns-job
      restartPolicy: Never
