---
apiVersion: v1
kind: ClusterRole
metadata:
  labels:
    {{- include "dev-pod.labels" . | nindent 4 }}
  name: {{ template "dev-pod.fullname" . }}-label-ns-job
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - update