---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  labels:
    {{- include "dev-pod.labels" . | nindent 4 }}
  name: dockerhub-regcred
spec:
  encryptedData:
    .dockerconfigjson: AgBUC7jE+zJYZFCFNPJ11A21zMhSRoGsEVcuD1GS9oQsJIOkNlJDu2VePBtRmVvpXHMom2IjK0qVNT6CSeDkzAONJjo3sypGJIudEN21iNez72v8tiWhWWJPF9XLO2Hl/EsBL1hwNUw9SkMnlphOItyqBFi44ytPPXWa5DJTbUPgG1bc6ZMaval8JYxmW3ecj/TMQL55Vf6i9lfc6la6yOUworwk6IeTVuiAVt7f6zaJtT2pkl+OhdhJpxYyvw76EbhDPEos8cdmfpnpriy+3144CYikAyUSNBRx8O55tnJl4rof3uJiAJah28L77tlqOrWvYKRqukHUQNQSKfrPm4c8gsxkunuXs9aNwGzyw7pmKinJNp0S5pWMjMNDDAiXYSg4nT6MrXViBeljCaTrs4wqdtLbWuTHMVJgh+f89RQyWvbqeq1NqGP6h+dgS4h8jpo/om8qO4hUcgzOS7zBuAOw//MOBol2SAxyV7I4wlqvNvd2lujQYCciVn85LdAPvH/dIrvFrgS4qDgRlIerGCD4jB5IHSXPv/x/qnVB/YTDN5UF7yxUDmTLHgLp1Yco9lzXQbLgJgeu4l1rcp8VDrbuQ8sVr0CCDSybPyliYVVEQsSCfskkpU3RCbqwWLi5Q/0PNqu3WZPn6phk4rpaMaV79+kyEE3TfAIYszEeuueAYrAh7j+9HHm3ykU8DSSFovL5OK+yY+WeJLnlqsxJd/RsnEMRFm5aa3VELQZIqs5nHU5z4Kfq4uIJrmqqgJPQorJAS9MF19ayC3/6vxoh7mqLWkfDjjaj7iny0xy7dB/Hd9vCZG2Wx9bkAPmJr8msStXugiXiCIfWKb7Hme/ZBfeQ/pW2qjWEsQ98yNuLXZOyVbaaeMTfbL/5EjiW63NDlNn4ZuzsiAtLjfuBYb6M4upp0LMajLIGoIlb50oAdwp3
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: dockerhub-regcred
      namespace: {{ .Release.Namespace }}
    type: kubernetes.io/dockerconfigjson
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  labels:
    {{- include "dev-pod.labels" . | nindent 4 }}
  name: github-token
spec:
  encryptedData:
    GH_TOKEN: AgCteud21al6gPR+EtF0hJRM+qSA3Z9afYuPjeRSTPB2R3oXy79AEargg05aE1t1TsQCSVGZ4IQm13cMjbHuGLo3fVZjMKkGWvq2kzyr8FcLYhcDjcu04C/br2IcxMNbyJWC5RfH3oyKlma4Es2NM2AwV4kCuXUKtFZXMq4wlurO+O6BNf7GfoL6xUVEV7uCmbfHFUMIuBgBUVv/3m100uQUyUpu4tHk5psXkogSFeSRFWHfYhGqYlPMWndxNmAJVL6t8xpnfuXvNLmJLVTkS368qwTnuSjzWF1wJNtwgTZwo4PaKAa8mLKgVvX/Hz/Yx/FayB+5PJbF6UNASojw7sC3FU6cXWDmxCHaMPASk4uOmENa3KnGv6D0FEx88KRNficPj6ZMWLkNxnBhHw2LCL3HwY4/z5SxM+QriYDJe02R0W+dLd/1b/pWfbwyBJg5kUghbCjEHTcwM9gBGTPlRXpj5yiAmezBhURPCg4G6s+liWMWd1ty7+QumIQJp5sWHSjaqRpCzlfHuL0bmooXaU4STpzpfXRrpmgSSkYeLcaJBKkRxiz0mqh8316QYYDXy9jTjdf8MUSVXYdWsebLlD6LKVeksnsS1TDGqA974SyLq5SdxLmOvCNHTUN5PVQwi/5tkSyarwWx3Hmu0GRuhGXiKNkizlKSe4h5oHOx3ZHKTQvvtbkm6wgfm8Y/fuHCQixSpFRHoxSL6+xZxZgFYcVT5Z6TQjrfBC+lqBbIYiTBSRn7rINkrNFp
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: github-token
      namespace: {{ .Release.Namespace }}
