---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "dev-pod.labels" . | nindent 4 }}
  annotations:
    load-balancer.hetzner.cloud/ipv6-disabled: "true"
    load-balancer.hetzner.cloud/location: ash
    load-balancer.hetzner.cloud/protocol: tcp
    external-dns.alpha.kubernetes.io/hostname: ubuntu-jump.k8s.unreliable.cloud
  name: {{ include "dev-pod.name" . }}-ssh
spec:
  selector:
    {{- include "dev-pod.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: ssh
    protocol: TCP
    name: ssh
  type: {{ .Values.service.type }}
  externalTrafficPolicy: Local