---
name: Build Container
on:
  pull_request:
    types: [ closed ]

env:
  REGISTRY: youvegotmoxie
  IMAGE_NAME: ubuntu-jump
  CONTEXT: docker
  REGISTRY_BASE: docker.io
  IMAGE_TAG: dev
  VALUES_FILE: kustomization.yaml

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout branch
        id: checkout_branch
        run: echo "::set-output name=GIT_TAG_NAME::$(git rev-parse --short HEAD)"
        if: github.event.pull_request.merged == true
      - uses: docker/login-action@v2
        if: github.event.pull_request.merged == true
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        if: github.event.pull_request.merged == true
        with:
          push: true
          tags: ${{ env.REGISTRY_BASE }}/${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          context: ${{ env.CONTEXT }}
      - uses: actions/checkout@v2
      - name: Update image tag
        if: github.event.pull_request.merged == true
        id: set_tag_name
        run: |
          sed -i "s|newTag: [a-z].*|newTag: ${{ env.IMAGE_TAG }}|" ./${{ env.VALUES_FILE }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        if: github.event.pull_request.merged == true
        with:
          commit_message: Automated Change
          commit_options: '--no-verify --signoff'
          commit_user_name: GitHub Actions
          commit_author: Author <github-actions@undependable.cloud>
          create_branch: false
          branch: master
      - uses: ravsamhq/notify-slack-action@master
        if: always()
        with:
          status: ${{ job.status }}
          notification_title: '[GitHub Actions] {workflow} has {status_message}'
          message_format: '{emoji} ${{ github.event.head_commit.author.name }} ${{ github.event.head_commit.message }}'
          footer: 'Repo: <{repo_url}|{repo}>'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
