---
name: Build Container (DevPod)
on:
  pull_request:
    types: [ closed ]

env:
  REGISTRY: youvegotmoxie
  IMAGE_NAME: devpod
  CONTEXT: docker
  REGISTRY_BASE: docker.io
  IMAGE_TAG: dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout branch
        id: checkout_branch
        run: echo "::set-output name=GIT_TAG_NAME::$(git rev-parse --short HEAD)"
        if: github.event.pull_request.merged == true
      - uses: docker/login-action@v2
        if: github.event.pull_request.merged == true
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: cosign-installer
        uses: sigstore/cosign-installer@v2.0.0
      - name: Output cosign private key
        run: 'echo "$KEY" > cosign.key'
        shell: bash
        env:
          KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
      - uses: docker/build-push-action@v3
        if: github.event.pull_request.merged == true
        with:
          push: true
          tags: ${{ env.REGISTRY_BASE }}/${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          context: ${{ env.CONTEXT }}
      - name: Sign Docker image
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: cosign sign --key cosign.key -a signed=github ${{ env.REGISTRY_BASE }}/${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      - uses: ravsamhq/notify-slack-action@master
        if: always()
        with:
          status: ${{ job.status }}
          notification_title: '[GitHub Actions] {workflow} has {status_message}'
          message_format: '{emoji} ${{ github.event.head_commit.author.name }} ${{ github.event.head_commit.message }}'
          footer: 'Repo: <{repo_url}|{repo}>'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
