name: Lint Code Base

on:
  pull_request:
    branches: [master, main]

env:
  CONTEXT: docker
  CHART_PATH: helm/dev-pod

jobs:
  lint-docker:
    name: Lint Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Lint Dockerfile
        uses: luke142367/Docker-Lint-Action@v1.0.0
        with:
          target: ${{ env.CONTEXT }}/Dockerfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  lint-helm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Lint Helm
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm dep up ${{ env.CHART_PATH }} && helm lint ./${{ env.CHART_PATH }}

